# Generated by Django 5.2.12 on 2026-04-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_phone_number_user_sharif_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('en', 'English'), ('ru', 'Русский')], default='uz', max_length=2),
        ),
    ]
