# Generated by Django 5.2.12 on 2026-04-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_language_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m/%d/'),
        ),
    ]
