# Generated by Django 5.2.12 on 2026-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tarif',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('pro', 'Pro')], default='Standard', max_length=20, null=True),
        ),
    ]
