# Generated by Django 5.2.12 on 2026-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_tarif'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('grant_name', models.CharField(max_length=100)),
                ('grand_amount', models.CharField(max_length=100)),
                ('grand_turi', models.CharField(max_length=50)),
                ('directions', models.CharField(max_length=50)),
                ('reception_start', models.DateField()),
                ('reception_end', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
