# Generated by Django 5.2.12 on 2026-04-18 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_tarif'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('grant_name', models.CharField(max_length=100)),
                ('grand_amount', models.CharField(max_length=100)),
                ('grand_turi', models.CharField(max_length=50)),
                ('directions', models.CharField(max_length=50)),
                ('reception_start', models.DateField()),
                ('reception_end', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Eslatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eslatma_matni', models.CharField(max_length=300)),
                ('ogohlantirish_sms', models.CharField(blank=True, choices=[('gmail', 'Gmail'), ('bot', 'Bot')], default='gmail', max_length=300, null=True, verbose_name='Ogohlantirish SMS matni')),
                ('eslatma_kun', models.DateField(blank=True, null=True, verbose_name='Eslatish sanasi')),
                ('chat_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='Telegram chat ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eslatma_user', to=settings.AUTH_USER_MODEL)),
                ('universitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eslatma_universitet', to='api.university')),
            ],
        ),
    ]
