# Generated by Django 5.2.12 on 2026-10-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_university_alter_user_email_eslatma'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='official_website',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Rasmiy sayt'),
        ),
    ]
