# Generated by Django 5.2.12 on 2026-04-14 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eslatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eslatma_matni', models.CharField(max_length=300)),
                ('eslatma_kun', models.DateField(blank=True, null=True, verbose_name='Eslatish sanasi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('universitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eslatma_universitet', to='api.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eslatma_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
