# Generated by Django 5.2.12 on 2026-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_eslatma'),
    ]

    operations = [
        migrations.AddField(
            model_name='eslatma',
            name='chat_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Telegram chat ID'),
        ),
        migrations.AddField(
            model_name='eslatma',
            name='ogohlantirish_sms',
            field=models.CharField(blank=True, choices=[('gmail', 'Gmail'), ('bot', 'Bot')], default='gmail', max_length=300, null=True, verbose_name='Ogohlantirish SMS matni'),
        ),
    ]
