# Generated by Django 5.2.12 on 2026-04-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_university_alter_user_email_eslatma'),
        ('api', '0009_eslatma_chat_id_eslatma_ogohlantirish_sms'),
    ]

    operations = [
    ]
