# Generated by Django 5.2.12 on 2026-10-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_university_official_website'),
        ('api', '0010_merge_20260419_1708'),
    ]

    operations = [
    ]
